# Generated by Django 5.2.4 on 2025-07-10 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query_params', models.TextField(blank=True, null=True)),
                ('request_headers', models.TextField(blank=True, null=True)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('response_status_code', models.IntegerField()),
                ('response_headers', models.TextField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('request_timestamp', models.DateTimeField()),
                ('response_timestamp', models.DateTimeField()),
                ('duration_ms', models.FloatField(help_text='Request duration in milliseconds')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('request_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_logs',
                'ordering': ['-request_timestamp'],
                'indexes': [models.Index(fields=['method', 'path'], name='api_logs_method_982fac_idx'), models.Index(fields=['request_timestamp'], name='api_logs_request_d14007_idx'), models.Index(fields=['response_status_code'], name='api_logs_respons_8f977a_idx'), models.Index(fields=['request_user'], name='api_logs_request_08707c_idx')],
            },
        ),
    ]
